"""给数据库增加创建时间更新时间

Revision ID: 14093fda54d7
Revises: f8283b6bbc43
Create Date: 2020-07-22 16:52:15.493379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14093fda54d7'
down_revision = 'f8283b6bbc43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('battle_detail', sa.Column('battle_ranking', sa.Integer(), nullable=True))
    op.add_column('battles', sa.Column('created_time', sa.DateTime(), nullable=True))
    op.add_column('battles', sa.Column('state', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'battles', ['id'])
    op.add_column('users', sa.Column('created_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created_time')
    op.drop_constraint(None, 'battles', type_='unique')
    op.drop_column('battles', 'state')
    op.drop_column('battles', 'created_time')
    op.drop_column('battle_detail', 'battle_ranking')
    # ### end Alembic commands ###
