"""增加updatetime

Revision ID: 792887fc9636
Revises: 14093fda54d7
Create Date: 2020-07-23 10:18:14.513419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '792887fc9636'
down_revision = '14093fda54d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('battles', sa.Column('updated_time', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('updated_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_time')
    op.drop_column('battles', 'updated_time')
    # ### end Alembic commands ###
