"""给玩家增加area—id 服务器字段

Revision ID: bb1be3b681a4
Revises: 854ab66292ce
Create Date: 2020-07-16 23:33:38.243446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb1be3b681a4'
down_revision = '854ab66292ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('area_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'area_id')
    # ### end Alembic commands ###
