"""创建装备表

Revision ID: bbe0b67a109d
Revises: 792887fc9636
Create Date: 2020-07-23 16:30:16.804528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbe0b67a109d'
down_revision = '792887fc9636'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('property', sa.Text(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('formula', sa.ARRAY(sa.Integer()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('battles', sa.Column('slol_id', sa.String(length=50), nullable=True, comment='来源玩家_id'))
    op.alter_column('battles', 'state',
               existing_type=sa.INTEGER(),
               comment='爬取状态',
               existing_nullable=True)
    op.add_column('chess', sa.Column('image', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chess', 'image')
    op.alter_column('battles', 'state',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='爬取状态',
               existing_nullable=True)
    op.drop_column('battles', 'slol_id')
    op.drop_table('items')
    # ### end Alembic commands ###
