"""'将比赛表的时间更改为开始时时间'

Revision ID: f8283b6bbc43
Revises: bb1be3b681a4
Create Date: 2020-07-17 17:22:36.293266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8283b6bbc43'
down_revision = 'bb1be3b681a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('battles',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('game_mode', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('chess',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tft_id', sa.Integer(), nullable=True),
    sa.Column('armor', sa.String(length=50), nullable=True),
    sa.Column('attack', sa.String(length=50), nullable=True),
    sa.Column('attack_data', sa.String(length=50), nullable=True),
    sa.Column('attack_mag', sa.String(length=50), nullable=True),
    sa.Column('attack_range', sa.String(length=50), nullable=True),
    sa.Column('attack_speed', sa.String(length=50), nullable=True),
    sa.Column('crit', sa.String(length=50), nullable=True),
    sa.Column('display_name', sa.String(length=50), nullable=True),
    sa.Column('illustrate', sa.String(length=50), nullable=True),
    sa.Column('job_ids', sa.String(length=50), nullable=True),
    sa.Column('jobs', sa.String(length=50), nullable=True),
    sa.Column('life', sa.String(length=50), nullable=True),
    sa.Column('life_data', sa.String(length=50), nullable=True),
    sa.Column('life_mag', sa.String(length=50), nullable=True),
    sa.Column('magic', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('original_image', sa.Text(), nullable=True),
    sa.Column('price', sa.String(length=50), nullable=True),
    sa.Column('pro_status', sa.String(length=50), nullable=True),
    sa.Column('race_ids', sa.String(length=50), nullable=True),
    sa.Column('races', sa.String(length=50), nullable=True),
    sa.Column('rec_equip', sa.Text(), nullable=True),
    sa.Column('skill_detail', sa.Text(), nullable=True),
    sa.Column('skill_image', sa.Text(), nullable=True),
    sa.Column('skill_introduce', sa.Text(), nullable=True),
    sa.Column('skill_name', sa.String(length=50), nullable=True),
    sa.Column('skill_type', sa.String(length=50), nullable=True),
    sa.Column('spell_block', sa.String(length=50), nullable=True),
    sa.Column('start_magic', sa.String(length=50), nullable=True),
    sa.Column('synergies', sa.String(length=50), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('battle_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('battle_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('gold_left', sa.Integer(), nullable=True),
    sa.Column('health', sa.Integer(), nullable=True),
    sa.Column('last_round', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('players_eliminated', sa.Integer(), nullable=True),
    sa.Column('show_last_round', sa.String(length=20), nullable=True),
    sa.Column('snapshot_time', sa.Integer(), nullable=True),
    sa.Column('snapshot_url', sa.String(length=50), nullable=True),
    sa.Column('time_eliminated', sa.Text(), nullable=True),
    sa.Column('total_damage_to_players', sa.Integer(), nullable=True),
    sa.Column('total_trait_num', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['battle_id'], ['battles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('battle_id', 'user_id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('battle_chess',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('battle_detail_id', sa.Integer(), nullable=True),
    sa.Column('items', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('hero_id', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('star', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['battle_detail_id'], ['battle_detail.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hero_id'], ['chess.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('battle_chess')
    op.drop_table('battle_detail')
    op.drop_table('chess')
    op.drop_table('battles')
    # ### end Alembic commands ###
